# A consolidated update of the simulation model.

# The timestamp associated with this state according to the time source, such
# as the controller.
builtin_interfaces/Time stamp

# The overall asteroid state.
asteroid_mining_interfaces/Asteroid asteroid

# The overall siphon state.
asteroid_mining_interfaces/Siphon siphon

# The overall released payload state.
asteroid_mining_interfaces/ReleasedPayload released_payload
